default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: Kaligo_development

test:
  <<: *default
  database: Kaligo_test
